name: Emscripten build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:         ["windows-latest", "ubuntu-20.04", "macos-14"]
        build_type: ["Debug", "Release"]
        include:
          - os:         "windows-latest"
            build_type: "Release"
            host_name:  "Win10"
            # Do not build WebGPU on Windows/Release as it is extremely slow
            cmake_args: "-DDILIGENT_NO_WEBGPU=ON -DDILIGENT_NO_ARCHIVER=ON"

          - os:         "windows-latest"
            build_type: "Debug"
            host_name:  "Win10"
            cmake_args: "-DDILIGENT_EMSCRIPTEN_STRIP_DEBUG_INFO=ON"

          - os:        "ubuntu-20.04"
            build_type: "Debug"
            host_name: "Linux"
            cmake_args: "-DDILIGENT_EMSCRIPTEN_STRIP_DEBUG_INFO=ON"

          - os:        "ubuntu-20.04"
            build_type: "Release"
            host_name: "Linux"
            # Do not build WebGPU on Linux/Release as it is extremely slow
            cmake_args: "-DDILIGENT_NO_WEBGPU=ON -DDILIGENT_NO_ARCHIVER=ON"

          - os:        "macos-14"
            build_type: "Debug"
            host_name: "MacOS"
            cmake_args: "-DDILIGENT_EMSCRIPTEN_STRIP_DEBUG_INFO=ON"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.host_name }} -> Emscripten, ${{ matrix.build_type }}

    steps:
    - name: Checkout
      uses: DiligentGraphics/github-action/checkout@v1

    - name: Set up build environment
      if:   success()
      uses: DiligentGraphics/github-action/setup-build-env@v1
      with:
        platform: Emscripten

    - name: Configure CMake
      if:   success()
      uses: DiligentGraphics/github-action/configure-cmake@v1
      with:
        build-type: ${{ matrix.build_type }}
        cmake-args: ${{ matrix.cmake_args }}

    - name: Build
      if:   success()
      uses: DiligentGraphics/github-action/build@v1
